name: angivy
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.3
  json_serializable:
dependencies:
  dotenv: ^4.0.1
  http: ^0.13.5
  get_code_status: ^1.0.1
  mysql1: ^0.20.0
  analyzer: ^5.4.0
  json_annotation: ^4.7.0
  shelf_router: ^1.1.3
  shelf: ^1.4.0



assets:
  - .env